### ISSUE TITLE
Specifying multiple host groups in one run of Ansible with unique hosts in each group

### ISSUE THREAD

**Issue by sjwl** [radekg/terraform-provisioner-ansible#104]
I want an inventory file that looks like this

```ini
[controller]
10.1.1.10
[infra]
10.1.1.11
```
Because I have a playbook task that looks like this:
```yaml
---
# loop through each backend supporting the cinder api proxy
# to ensure they are up.
- name: checking cinder api haproxy backend
  haproxy:
    state: enabled
    host: "controller{{ item[0] }}"
    backend: cinder_api
    wait: yes
    wait_interval: 1
  delegate_to: "{{ item[1] }}"
  with_nested:
    - "{{ range(groups['controller'] | length) | list }}"
    - "{{ groups['infra'] }}"
```

Notice the task references both `controller` and `infra` host group.

So I tried something like this:
```hcl
resource "openstack_compute_instance_v2" "infra" {
    name = "infra"
    image_name = "ubuntu-18.04"

    network {
        name = "public"
    }
}

resource "openstack_compute_instance_v2" "controller" {
    name = "controller-${random_string.unique.result}"
    image_name = "ubuntu-18.04"

    network {
        name = "public"
    }
}

resource "null_resource" "openstack-playbook" {

    provisioner "ansible" {
        connection {
            user = "ubuntu"
            private_key = "${var.ssh_private_key}"
        }
        plays  {
             groups = ["infra"]
             hosts = ["${openstack_compute_instance_v2.infra.access_ip_v4}"]            
             playbook {
                 file_path = "../playbook.yml"
             }      
        }
        plays  {
             groups = ["controller"]
             hosts = ["${openstack_compute_instance_v2.controller.access_ip_v4}"]        
             playbook {
                 file_path = "../playbook.yml"
             }                      
        }              
    }
}
```

But this fails with `Error: Local mode requires a connection with username and host`

It appears each provisioner run _instance_ will only connect to a _single_ Ansible host, regardless how many `plays.hosts` are specified.
